version: '3.8'

services:
  nevera:
    # En Swarm, las imágenes deben estar pre-construidas y en un registro.
    # Reemplaza 'tu_usuario/nevera' con el nombre real de tu imagen.
    image: tu_usuario/vorak-nevera:latest
    container_name: vorak-nevera
    restart: unless-stopped
    environment:
      # Las variables no secretas se mantienen aquí.
      - FRIDGE_ID=${FRIDGE_ID}
      - BASE_BACKEND_URL=${BASE_BACKEND_URL}
      - CAMERA_DEVICES=/dev/video0,/dev/video1
    # El mapeo de dispositivos se hace a través de volúmenes, ya que 'devices' no es soportado.
    # Esto requiere que el servicio se ejecute en un nodo específico.
    volumes:
      - /dev/v4l/by-id:/dev/v4l/by-id:ro
      - /dev/ttyUSB0:/dev/ttyUSB0
      - nevera_offline_queue:/app/offline_queue
      - nevera_review_queue:/app/review_queue
      - nevera_logs:/app/logs
      - nevera_db:/app/db
      - fridge_status:/app/status
    secrets:
      - fridge_secret
    deploy:
      replicas: 1
      placement:
        constraints:
          # ¡IMPORTANTE! Esto fija el servicio al nodo con la etiqueta 'has_hardware=true'.
          - node.labels.has_hardware == true

  kiosko:
    image: tu_usuario/vorak-kiosko:latest
    container_name: vorak-kiosko
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
      - BASE_BACKEND_URL=${BASE_BACKEND_URL}
      - FRIDGE_ID=${FRIDGE_ID}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - fridge_status:/app/status:ro
      - kiosk_data:/app/data
    secrets:
      - fridge_secret
    deploy:
      replicas: 1
      placement:
        constraints:
          # El kiosko también debe correr en la misma máquina que la nevera.
          - node.labels.has_hardware == true

# Los volúmenes se definen igual. Swarm los gestionará.
volumes:
  nevera_offline_queue:
  nevera_review_queue:
  nevera_logs:
  nevera_db:
  fridge_status:
  kiosk_data:

# Aquí se declaran los secretos que los servicios usarán.
secrets:
  fridge_secret:
    # 'external: true' le dice a Swarm que el secreto ya existe y no debe crearlo.
    external: true