global:
  scrape_interval: 15s

# Configuración para enviar métricas a un endpoint remoto (Grafana Cloud).
# Utiliza variables de entorno que se definen en el archivo .env y se pasan
# a través de docker-compose.yml o docker-stack.monitoring.yml.
remote_write:
  - url: "${GRAFANA_CLOUD_PROMETHEUS_URL}"
    basic_auth:
      username: "${GRAFANA_CLOUD_PROMETHEUS_USER}"
<<<<<<< HEAD
      # Lee la clave directamente del secreto de Docker, que se monta en esta ruta.
      password_file: /run/secrets/grafana_cloud_prometheus_api_key
=======
      password_file: "/run/secrets/grafana_cloud_prometheus_api_key"

>>>>>>> 427a20a (compose funcionando)
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names: ['tasks.cadvisor']
        type: 'A'
        port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names: ['tasks.node-exporter']
        type: 'A'
        port: 9100

  - job_name: 'vorak-app'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_docker_task_label_monitor_job]
        regex: .+
        action: keep
