global:
  scrape_interval: 60s

remote_write:
  - url: "${GRAFANA_CLOUD_PROMETHEUS_URL}" # Se lee desde el entorno
    basic_auth:
      username: "${GRAFANA_CLOUD_PROMETHEUS_USER}" # Se lee desde el entorno
      password_file: "/run/secrets/grafana_cloud_prometheus_api_key" # Se lee desde un secreto de Docker

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]    


  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
