server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "${GRAFANA_CLOUD_LOKI_URL}"
    basic_auth:
      username: "${GRAFANA_CLOUD_LOKI_USER}"
      # Lee la clave directamente del secreto de Docker. Asumimos que es la misma clave para Loki y Prometheus.
      password_file: /run/secrets/grafana_cloud_loki_api_key

scrape_configs:
  - job_name: container_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_logging_app']
        target_label: 'app'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_node_id']
        target_label: 'node'
